openapi: 3.0.0
info:
  title: Movie Viewer API
  description: An API to get information about movies and their viewers.
  version: 1.0.0

paths:
  /vod_movies:
    get:
      operationId: "movies.read_movies"
      summary: Get movies and viewers
      description: Returns a list of movies along with the number of viewers.
      parameters:
        - name: num_movies
          in: query
          description: The number of movies to return
          required: true
          schema:
            type: integer
            minimum: 1
        - name: num_viewers
          in: query
          description: The number of viewers to return
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: A list of movies with the number of viewers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VodMovieViewing'
        '400':
          description: Invalid request parameters
components:
  schemas:
    VodMovieViewing:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        genre:
          type: string
        release_year:
          type: integer