swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /movies:
    get:
      operationId: "movies.read_movies"
      tags:
        - "Movies"
      summary: "The prog data structure supported by the server application"
      description: "Read movies" 
      responses:
        200:
          description: "Successful read movies operation"
          schema:
            type: "array"
  /nodes:
    get:
      operationId: "progs.read_nodes"
      tags:
        - "Progs"
      summary: "The prog data structure supported by the server application"
      description: "Read a the prog network nodes"
      responses:
        200:
          description: "Successful read progs nodes operation"
          schema:
            type: "array"
            items:
              properties:
                name:
                  type: "string"
                group:
                  type: "integer"
  /links:
    get:
      operationId: "progs.read_links"
      tags:
        - "Progs"
      summary: "The prog data structure supported by the server application"
      description: "Read a the prog network links"
      responses:
        200:
          description: "Successful read progs links operation"
          schema:
            type: "array"
            items:
              properties:
                source:
                  type: "integer"
                target:
                  type: "integer"
                value:
                  type: "integer"
